### ISSUE TITLE
Preference Menu is Unreadable

### ISSUE THREAD

**Issue by reparke** [aCluelessDanny/typora-theme-ursine#31] opened 2019-08-13 22:56 UTC
In UrsinePolar, the currently selected menu option is unreadable

![image](https://user-images.githubusercontent.com/11014413/62983034-dbd5ef00-bde2-11e9-9d35-03e80974d1ef.png)

**Comment by aCluelessDanny** [comment] 2019-08-15 04:13
Duplicate of #27. I'll be getting to that in a bit~

**Closed by aCluelessDanny** 2019-08-15 04:13 UTC
